// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: order.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    user_id,
    event_id,
    total_price
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, event_id, created_at, total_price
`

type CreateOrderParams struct {
	UserID     *int64 `json:"user_id"`
	EventID    int64  `json:"event_id"`
	TotalPrice int32  `json:"total_price"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.EventID, arg.TotalPrice)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
		&i.TotalPrice,
	)
	return i, err
}
